version: "3.8"
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: tattoo-app-db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: tattoo-app-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  pgdata: "tattoo-app-db"