version: "3.8"
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: test-tattoo-db
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: test-tattoo-db
    ports:
      - "5432:5432"
    volumes:
      - test_pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  test_pgdata: "test-tattoo-db"